# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lmu-athlete-svc

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
  stage: prod
  region: us-west-2

functions:
  list:
    handler: handler.get
    timeout: 3
    events:
      - http:
          path: athletes
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_KMI3gTfQw
  get:
    handler: handler.get
    timeout: 3
    events:
      - http:
          path: athletes/{aid}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_KMI3gTfQw
  create:
    handler: handler.create
    timeout: 3
    events:
      - http:
          path: athletes
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_KMI3gTfQw
  update:
    handler: handler.update
    timeout: 3
    events:
      - http:
          path: athletes
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_KMI3gTfQw
  delete:
    handler: handler.delete
    timeout: 3
    events:
      - http:
          path: athletes/{aid}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:236711959566:userpool/us-west-2_KMI3gTfQw